name: solar-env
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
# === Core ===
  - python=3.12
  - pip

# === Data Science & Physics ===
  - numpy>=2.0             
  - pandas>=2.3
  - pvlib                  
  - scikit-learn
  - matplotlib>=3.10       
  - ipywidgets

# === Mapping & Geometry ===
  - geopandas
  - shapely>=2.1
  - folium>=0.20
  - mercantile
  - geopy
  - scikit-image>=0.26
  - osmnx
  - pytz                   

# === Machine Learning ===
  - pytorch                
  - torchvision
  - torchaudio
  - tqdm
  - pycocotools
  - rasterio

# === Web App ===
  - streamlit>=1.52
  - Pillow>=12.0

# === Google Services ===
  - googlemaps             
  - requests

# === Pip Packages ===
  - pip:
    - llama-index-llms-google-genai
    - opencv-python-headless==4.12.0.88
    - streamlit-folium==0.25.3
    - streamlit-drawable-canvas==0.9.3
    - segmentation-models-pytorch   
    - pysolar>=0.10  
    - groq               
