"""
Email Service for Quote Requests
Sends formatted emails to solar dealers with system specifications.
"""

import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Optional
from dataclasses import dataclass
from datetime import datetime


@dataclass
class QuoteEmailData:
    """Data structure for quote request emails."""
    # Dealer info
    dealer_name: str
    dealer_email: str

    # System specifications
    system_kwp: float
    panel_count: int
    roof_area_sqm: float
    roof_tilt: float
    roof_orientation: str
    estimated_production: float
    installation_address: str
    lat: float
    lon: float

    # Customer info
    customer_name: str
    customer_email: str
    customer_phone: Optional[str] = None
    additional_notes: Optional[str] = None

    # Options
    include_battery: bool = False
    include_financing: bool = False
    include_permits: bool = False

    # Tracking
    inquiry_id: Optional[str] = None


def get_smtp_config() -> dict:
    """Get SMTP configuration from environment variables."""
    return {
        "host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
        "port": int(os.getenv("SMTP_PORT", "587")),
        "user": os.getenv("SMTP_USER", ""),
        "password": os.getenv("SMTP_PASSWORD", ""),
        "from_name": os.getenv("SMTP_FROM_NAME", "SolarSight AI"),
    }


def format_quote_email_text(data: QuoteEmailData) -> str:
    """Format the quote request as plain text."""

    # Build options list
    options = []
    if data.include_battery:
        options.append("Include battery storage options")
    if data.include_financing:
        options.append("Interested in financing")
    if data.include_permits:
        options.append("Need permit assistance")

    options_text = "\n".join(f"  - {opt}" for opt in options) if options else "  None specified"

    text = f"""
Solar Installation Quote Request
================================

A potential customer has requested a quote through SolarSight AI.

SYSTEM SPECIFICATIONS
---------------------
System Size:        {data.system_kwp:.2f} kWp
Panel Count:        {data.panel_count} panels
Roof Area:          {data.roof_area_sqm:.1f} m²
Roof Tilt:          {data.roof_tilt:.0f}°
Roof Orientation:   {data.roof_orientation}
Est. Annual Output: {data.estimated_production:,.0f} kWh/year

INSTALLATION ADDRESS
--------------------
{data.installation_address}
Coordinates: {data.lat:.6f}, {data.lon:.6f}

CUSTOMER CONTACT
----------------
Name:  {data.customer_name}
Email: {data.customer_email}
Phone: {data.customer_phone or 'Not provided'}

ADDITIONAL REQUESTS
-------------------
{options_text}

CUSTOMER NOTES
--------------
{data.additional_notes or 'No additional notes'}

---
This quote request was generated by SolarSight AI
Inquiry ID: {data.inquiry_id or 'N/A'}
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}

Please respond directly to the customer at: {data.customer_email}
"""
    return text.strip()


def format_quote_email_html(data: QuoteEmailData) -> str:
    """Format the quote request as HTML."""

    # Build options checkboxes
    battery_check = "☑" if data.include_battery else "☐"
    financing_check = "☑" if data.include_financing else "☐"
    permits_check = "☑" if data.include_permits else "☐"

    html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
        .container {{ max-width: 600px; margin: 0 auto; padding: 20px; }}
        .header {{ background: linear-gradient(135deg, #f39c12, #f1c40f); color: white; padding: 20px; border-radius: 8px 8px 0 0; }}
        .header h1 {{ margin: 0; font-size: 24px; }}
        .section {{ background: #f9f9f9; padding: 15px; margin: 10px 0; border-radius: 4px; border-left: 4px solid #f39c12; }}
        .section h3 {{ margin-top: 0; color: #2c3e50; }}
        .specs-table {{ width: 100%; border-collapse: collapse; }}
        .specs-table td {{ padding: 8px 0; border-bottom: 1px solid #eee; }}
        .specs-table td:first-child {{ font-weight: bold; width: 40%; }}
        .customer-info {{ background: #e8f4fd; border-left-color: #3498db; }}
        .options {{ font-size: 14px; }}
        .footer {{ font-size: 12px; color: #666; margin-top: 20px; padding-top: 15px; border-top: 1px solid #ddd; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>☀️ Solar Installation Quote Request</h1>
            <p style="margin: 5px 0 0 0;">via SolarSight AI</p>
        </div>

        <div class="section">
            <h3>📊 System Specifications</h3>
            <table class="specs-table">
                <tr><td>System Size</td><td><strong>{data.system_kwp:.2f} kWp</strong></td></tr>
                <tr><td>Panel Count</td><td>{data.panel_count} panels</td></tr>
                <tr><td>Roof Area</td><td>{data.roof_area_sqm:.1f} m²</td></tr>
                <tr><td>Roof Tilt</td><td>{data.roof_tilt:.0f}°</td></tr>
                <tr><td>Orientation</td><td>{data.roof_orientation}</td></tr>
                <tr><td>Est. Production</td><td><strong>{data.estimated_production:,.0f} kWh/year</strong></td></tr>
            </table>
        </div>

        <div class="section">
            <h3>📍 Installation Address</h3>
            <p style="margin: 0;">{data.installation_address}</p>
            <p style="margin: 5px 0 0 0; font-size: 12px; color: #666;">
                Coordinates: {data.lat:.6f}, {data.lon:.6f}
            </p>
        </div>

        <div class="section customer-info">
            <h3>👤 Customer Contact</h3>
            <table class="specs-table">
                <tr><td>Name</td><td><strong>{data.customer_name}</strong></td></tr>
                <tr><td>Email</td><td><a href="mailto:{data.customer_email}">{data.customer_email}</a></td></tr>
                <tr><td>Phone</td><td>{data.customer_phone or 'Not provided'}</td></tr>
            </table>
        </div>

        <div class="section">
            <h3>✅ Additional Requests</h3>
            <div class="options">
                <p>{battery_check} Include battery storage options</p>
                <p>{financing_check} Interested in financing</p>
                <p>{permits_check} Need permit assistance</p>
            </div>
        </div>

        {"<div class='section'><h3>📝 Customer Notes</h3><p>" + data.additional_notes + "</p></div>" if data.additional_notes else ""}

        <div class="footer">
            <p>📧 Please respond directly to the customer at: <a href="mailto:{data.customer_email}">{data.customer_email}</a></p>
            <p>Inquiry ID: {data.inquiry_id or 'N/A'} | Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
            <p style="color: #999;">This quote request was automatically generated by SolarSight AI</p>
        </div>
    </div>
</body>
</html>
"""
    return html.strip()


def send_quote_email(data: QuoteEmailData) -> tuple[bool, str]:
    """
    Send a quote request email to the dealer.

    Args:
        data: QuoteEmailData containing all information

    Returns:
        Tuple of (success: bool, message: str)
    """
    config = get_smtp_config()

    if not config["user"] or not config["password"]:
        return False, "Email not configured. Please set SMTP_USER and SMTP_PASSWORD environment variables."

    if not data.dealer_email:
        return False, "Dealer email address not available."

    try:
        # Create message
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Quote Request: {data.system_kwp:.1f} kWp Solar System - {data.installation_address.split(',')[0]}"
        msg["From"] = f"{config['from_name']} <{config['user']}>"
        msg["To"] = data.dealer_email
        msg["Reply-To"] = data.customer_email

        # Attach both plain text and HTML versions
        text_part = MIMEText(format_quote_email_text(data), "plain", "utf-8")
        html_part = MIMEText(format_quote_email_html(data), "html", "utf-8")

        msg.attach(text_part)
        msg.attach(html_part)

        # Send email
        with smtplib.SMTP(config["host"], config["port"]) as server:
            server.starttls()
            server.login(config["user"], config["password"])
            server.send_message(msg)

        return True, f"Quote request sent successfully to {data.dealer_name}"

    except smtplib.SMTPAuthenticationError:
        return False, "Email authentication failed. Please check SMTP credentials."
    except smtplib.SMTPException as e:
        return False, f"Failed to send email: {str(e)}"
    except Exception as e:
        return False, f"Unexpected error: {str(e)}"


def send_confirmation_email(
    customer_email: str,
    customer_name: str,
    dealer_name: str,
    system_kwp: float
) -> tuple[bool, str]:
    """
    Send a confirmation email to the customer.

    Args:
        customer_email: Customer's email address
        customer_name: Customer's name
        dealer_name: Name of the dealer contacted
        system_kwp: System size requested

    Returns:
        Tuple of (success: bool, message: str)
    """
    config = get_smtp_config()

    if not config["user"] or not config["password"]:
        return False, "Email not configured"

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"Quote Request Confirmation - SolarSight AI"
        msg["From"] = f"{config['from_name']} <{config['user']}>"
        msg["To"] = customer_email

        text = f"""
Hello {customer_name},

Your quote request has been sent successfully!

Details:
- Dealer: {dealer_name}
- System Size: {system_kwp:.2f} kWp

The dealer should contact you within 1-2 business days.

Best regards,
SolarSight AI Team
"""

        html = f"""
<!DOCTYPE html>
<html>
<body style="font-family: Arial, sans-serif; line-height: 1.6;">
    <div style="max-width: 500px; margin: 0 auto; padding: 20px;">
        <h2 style="color: #f39c12;">☀️ Quote Request Sent!</h2>
        <p>Hello {customer_name},</p>
        <p>Your quote request has been sent successfully to <strong>{dealer_name}</strong>.</p>
        <div style="background: #f9f9f9; padding: 15px; border-radius: 4px; margin: 15px 0;">
            <p style="margin: 0;"><strong>System Size:</strong> {system_kwp:.2f} kWp</p>
        </div>
        <p>The dealer should contact you within 1-2 business days.</p>
        <p style="color: #666; font-size: 14px;">Best regards,<br>SolarSight AI Team</p>
    </div>
</body>
</html>
"""

        msg.attach(MIMEText(text, "plain", "utf-8"))
        msg.attach(MIMEText(html, "html", "utf-8"))

        with smtplib.SMTP(config["host"], config["port"]) as server:
            server.starttls()
            server.login(config["user"], config["password"])
            server.send_message(msg)

        return True, "Confirmation sent"

    except Exception as e:
        return False, str(e)


if __name__ == "__main__":
    # Test email formatting
    test_data = QuoteEmailData(
        dealer_name="SolarTech Berlin GmbH",
        dealer_email="test@example.com",
        system_kwp=5.2,
        panel_count=13,
        roof_area_sqm=32.5,
        roof_tilt=35,
        roof_orientation="South-West",
        estimated_production=4850,
        installation_address="Hauptstraße 123, 12345 Berlin",
        lat=52.5200,
        lon=13.4050,
        customer_name="Max Mustermann",
        customer_email="max@example.com",
        customer_phone="+49 170 1234567",
        additional_notes="We also have a flat garage roof that might be suitable.",
        include_battery=True,
        include_financing=True,
        inquiry_id="INQ-042"
    )

    print("=== Plain Text Version ===")
    print(format_quote_email_text(test_data))

    print("\n=== HTML Version ===")
    print(format_quote_email_html(test_data))
